name: CI/CD

on: push

jobs:
  # CI:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: 14.0.0
  #   - run: |
  #       npm i
  #       npm test --if-present
      
  #     name: CI
  #     env:
  #       CI: true


  CD:
    runs-on: ubuntu-latest
    
    # needs: CI

    steps: 
    - uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ~/nginxOnTheFlySetup
          git pull
          source ~/.nvm/nvm.sh
          nvm use default
          npm i
          npm run build --if-present
          node pm2Reload
